services:
  init-catalog:
    image: ${OKTETO_BUILD_CATALOG_IMAGE}
    command: yarn load
    environment:
      - MONGODB_USERNAME=okteto
      - MONGODB_PASSWORD=mongodb123
      - MONGODB_DATABASE=okteto
      - MONGODB_HOST=mongodb-catalog
    restart: never
    depends_on:
      mongodb-catalog:
        condition: service_healthy

  mongodb-catalog:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodb123root
      - MONGO_INITDB_DATABASE=okteto
    ports:
      - 27017
    volumes:
      - data-catalog:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  data-catalog: